#!/usr/bin/env python3
"""Parse vocab_raw.txt, add hiragana reading via pykakasi, emit vocab-data.js."""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

from pykakasi import kakasi

ROOT = Path(__file__).resolve().parent
RAW = ROOT / "vocab_raw.txt"
OUT = ROOT / "vocab-data.js"
DOCS = ROOT / "docs"
INDEX_HTML = ROOT / "index.html"

LINE_RE = re.compile(r"^(.+?)（(.+?)）\s*$")
KKS = kakasi()


def normalize_hv(s: str) -> str:
    s = s.strip()
    if "/" in s:
        s = s.split("/")[0].strip()
    return s


def kanji_chars(word: str) -> list[str]:
    return [c for c in word if "\u4e00" <= c <= "\u9fff" or c in "々"]


def hv_tokens(hv: str) -> list[str]:
    return [t for t in re.split(r"\s+", normalize_hv(hv)) if t]


def assign_char_hv(word: str, hv: str) -> list[dict]:
    chars = kanji_chars(word)
    tokens = hv_tokens(hv)
    out = []
    if not chars:
        return out
    while len(tokens) < len(chars) and tokens:
        tokens.append(tokens[-1])
    if len(tokens) >= len(chars):
        for i, ch in enumerate(chars):
            out.append({"char": ch, "hv": tokens[i].lower()})
        return out
    if len(tokens) == 1 and len(chars) > 1:
        t = tokens[0].lower()
        for ch in chars:
            out.append({"char": ch, "hv": t})
        return out
    while len(tokens) < len(chars):
        tokens.append(tokens[-1] if tokens else "")
    for i, ch in enumerate(chars):
        out.append({"char": ch, "hv": (tokens[i] or "").lower()})
    return out


def word_to_hiragana(word: str) -> str:
    parts = KKS.convert(word)
    return "".join(p["hira"] for p in parts)


def make_easy_ja(word: str, on: str) -> str:
    """Short やさしい日本語 explanation (exam-vocab template)."""
    chars = kanji_chars(word)
    n = len(chars)
    if n >= 3:
        tail = f"{n}つの漢字が並んだ言葉です。"
    elif n == 2:
        tail = "二つの漢字が組み合わさった言葉です。"
    else:
        tail = "漢字の言葉です。"
    on_part = on or "（読みは辞書で確認しましょう）"
    return (
        f"「{word}」は「{on_part}」と読みます。"
        f"{tail}"
        f"介護や福祉の文章や、国家試験の準備でよく使う言葉の一つです。"
    )


def main():
    lines = [ln.strip() for ln in RAW.read_text(encoding="utf-8").splitlines()]
    lines = [ln for ln in lines if ln]
    entries = []
    for i, ln in enumerate(lines):
        m = LINE_RE.match(ln)
        if not m:
            print("SKIP:", ln[:60])
            continue
        word, hv = m.group(1).strip(), m.group(2).strip()
        hv_display = normalize_hv(hv).lower()
        try:
            on = word_to_hiragana(word)
        except Exception:
            on = ""
        entries.append(
            {
                "id": i,
                "word": word,
                "hv": hv_display,
                "on": on,
                "kanji": assign_char_hv(word, hv),
                "easyJa": make_easy_ja(word, on),
            }
        )

    print("entries:", len(entries))

    char_index: dict[str, list] = {}
    for e in entries:
        for ch in set(kanji_chars(e["word"])):
            char_index.setdefault(ch, []).append(
                {"id": e["id"], "word": e["word"], "hv": e["hv"]}
            )

    payload = {"entries": entries, "charIndex": char_index}

    js_body = (
        "// Auto-generated by build_vocab.py\n"
        "window.VOCAB_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUT.write_text(js_body, encoding="utf-8")
    print("Wrote", OUT)

    # Mirror for GitHub Pages when "Source" is /docs (common default)
    DOCS.mkdir(exist_ok=True)
    (DOCS / "vocab-data.js").write_text(js_body, encoding="utf-8")
    print("Wrote", DOCS / "vocab-data.js")
    if INDEX_HTML.is_file():
        shutil.copy2(INDEX_HTML, DOCS / "index.html")
        print("Copied", INDEX_HTML, "->", DOCS / "index.html")
    (DOCS / ".nojekyll").touch()


if __name__ == "__main__":
    main()
